marketplace/blog/urls.py
from django.urls import path
from . import views
from .views import PostLikeToggle

app_name = 'blog'


urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<slug:slug>/", views.blogpost_detail, name="blogpost_detail"),
    path("<slug:slug>/like/", PostLikeToggle.as_view(), name="like-toggle"),
    path("category/<category>/", views.blog_category, name="blog_category"),
    path("<int:pk>/comment_like/", views.like_comment, name="like"),  # is not used right now
]

marketplace/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new.html/', views.new, name='new'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/like/', views.like_item, name="like-toggle"),

]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/item/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.conf import settings
import time


class Category(models.Model):
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, default='category')
    image = models.ImageField(upload_to='category_images', blank=True, null=True)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Location(models.Model):
    region = models.CharField(max_length=255, default="Минская обл.")
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Locations'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    slug = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    is_rateable = models.BooleanField(default=False)
    is_usd = models.BooleanField(default=True)
    is_moderated = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='created', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    location = models.ForeignKey(Location, related_name='locations', on_delete=models.CASCADE, default=1)
    liked_by = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='items_liked', blank=True)

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, time.time())
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Cars(models.Model):
    pass

marketplace/item/forms.py
from django import forms
from .models import Item

INPUT_CLASSES = 'bg-gray-50 border border-gray-300 text-gray-900 text-sm ' \
                'rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ' \
                'p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 ' \
                'dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image', 'location')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'location': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold', 'location')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'location': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

marketplace/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from django.core.paginator import Paginator
from django.db.models import Q
from .forms import NewItemForm, EditItemForm
from .models import Item, Category


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    pagination_items = Item.objects.filter(is_sold=False)
    items = Item.objects.filter(is_sold=False, is_moderated=True).order_by('created_at').reverse()

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    # paginator code
    paginator = Paginator(items, 15)
    page = request.GET.get('page')
    items = paginator.get_page(page)

    return render(request, 'item/items.html', {
        'items': items,
        'pagination_items': pagination_items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


def category_detail(request, slug):
    categories = Category.objects.all()
    category = get_object_or_404(Category, slug=slug)
    category_id = request.GET.get('category', 0)
    items = category.items.filter(is_sold=False, is_moderated=True)

    if category_id:
        items = items.filter(category_id=category_id)

    return render(request, 'item/category_detail.html', {
        'category': category,
        'items': items,
        'categories': categories,
        'category_id': int(category_id),
    })


def detail(request, category_slug, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False, is_moderated=True).order_by('created_at').reverse().exclude(pk=pk)[0:8]
    price_usd = item.price * 0.31
    price_byn = item.price / 0.31

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        'price_usd': price_usd,
        'price_byn': price_byn,
    })


class ItemLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        category = self.kwargs.get("slug")
        pk = self.kwargs.get("pk")
        obj = Item.objects.get(pk=pk)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.liked_by.all():
                obj.liked_by.remove(user)
            else:
                obj.liked_by.add(user)
        return url_


def like_item(request, pk):
    item = get_object_or_404(Item, id=pk)

    if item.liked_by.filter(id=request.user.id).exists():
        item.liked_by.remove(request.user)
    else:
        item.liked_by.add(request.user)


@login_required()
def new(request):
    if request.method == "POST":
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail', category_slug=item.category.slug, id=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })


@login_required()
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail', category_slug=item.category.slug, pk=item.pk)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

marketplace/item/templates/item/category_detail.html
{% extends 'core/base.html' %}
{% load menu %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}


{% menu %}

  <div class="container mx-auto">
              <h1 class="title-font sm:text-2xl text-3xl mb-4 ml-2 font-medium text-gray-900">Категория <span class="text-indigo-600">{{ category.name }}</span></h1>

    <div class="flex flex-wrap mt-2">
      <!--Categories loop-->
        {% for subcategory in category.children.all %}
      <div class="lg:w-1/5 md:w-1/2 p-1 w-full">
        <!-- OLD url  <a href="{% url 'item:items' %}?query={{ query }}&category={{ subcategory.id }}" class="block relative rounded overflow-hidden"> -->
        <!-- OLD url  <a href="{% url 'item:items' %}?query={{ query }}&category={{ subcategory.id }}" class="block relative rounded overflow-hidden"> -->
        <a href="{% url 'item:category_detail' subcategory.slug %}" class="block relative rounded overflow-hidden">
          <img alt="{{ subcategory.name }}" class="h-48 w-full object-cover object-center block rounded-t-xl" src="{{ subcategory.image_url|default_if_none:'/media/item_images/default.png' }}">

        <div class="bg-gray-100 rounded-b-xl p-2">
          <h3 class="text-gray-500 text-xs tracking-widest title-font">Объявлений: {{ subcategory.items.count }}</h3>
          <h2 class="text-gray-700 title-font text-base font-medium">{{ subcategory.name }}</h2>
		</div>
			</a>
      </div>
      {% endfor %}
      <!--End Categories loop-->
      </div>

  <div class="container mx-auto">
    <div class="flex flex-wrap mt-2">
      <!--Items loop-->
      {% if items.count == 0 and category.children.all.count == 0 %}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">В категории <span class="text-indigo-600">{{ category.name }}</span>
        <br class="hidden lg:inline-block">еще нет объявлений
      </h1>
      <p class="mb-8 leading-relaxed">Вы можете стать первым! Для того, чтобы добавить новое объявление, нужно быть зарегестрированным пользователем и нажать "Новое объявление".</p>
      <div class="flex justify-center">
          <a href="{% url 'item:new' %}">
              <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-4 focus:outline-none hover:bg-indigo-600 rounded text-base">Новое объявление
        		<svg class="ml-1.5 w-5 h-5" viewBox="0 -7 26 26" xmlns="http://www.w3.org/2000/svg" fill="none"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path fill="white" fill-rule="evenodd" d="M10 3a7 7 0 100 14 7 7 0 000-14zm-9 7a9 9 0 1118 0 9 9 0 01-18 0zm14 .069a1 1 0 01-1 1h-2.931V14a1 1 0 11-2 0v-2.931H6a1 1 0 110-2h3.069V6a1 1 0 112 0v3.069H14a1 1 0 011 1z"></path> </g></svg>
                </button>
          </a>
        <a href="/"><button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-base">На главную</button></a>
          </div>
        </div>

      <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <img alt="{{ category.name }}" class="object-cover object-center max-w-96 rounded-xl" alt="hero" src="{{ category.image_url|default_if_none:'/media/item_images/default.png' }}">
    </div>
  </div>
</section>

        {% else %}
        {% endif %}

            {% if category.children.all.count > 0 %}
            <section class="text-gray-600 body-font">
            <div class="container px-5 py-24 mx-auto">
              <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto">
                <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Не нашли желаемую категорию? Предложите ее Нам, и мы сделаем сайт лучше для Вас.</h1>
                <a href="/contact/"><button class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">Связаться</button></a>
              </div>
            </div>
          </section>
          {% else %}
        {% endif %}

       {% for item in items %}
      <div class="lg:w-1/5 md:w-1/2 p-1 w-full">
        <a href="{% url 'item:detail' item.category.slug  item.pk %}" class="block relative rounded overflow-hidden">
          <img alt="{{ item.name }}" class="h-48 w-full object-cover object-center block rounded-t-xl" src="{{ item.image_url|default_if_none:'/media/item_images/default.png' }}">

        <div class="bg-gray-100 rounded-b-xl p-2">
          <h3 class="text-gray-500 text-xs tracking-widest title-font"> {{ item.category }}</h3>
          <h2 class="text-gray-700 title-font text-base font-medium">{{ item.name }}</h2>
          <p class="text-sm mb-1">${{ item.price|floatformat:0 }}</p>
		</div>
			</a>
      </div>
      {% endfor %}
      <!--End items loop-->
              </div>
          </div>
        </div>
    </div>
  </div>


{% endblock %}

marketplace/item/templates/item/items.html
{% extends 'core/base.html' %}
{% load menu %}
{% block title %}Объявления{% endblock %}
{% block content %}



{% menu %}

  <div class="container mx-auto">
    <div class="flex flex-wrap mt-2">
      <!--Items loop-->
       {% for item in items %}
      <div class="lg:w-1/5 md:w-1/2 p-1 w-full overflow-hidden relative">
        <a href="{% url 'item:detail' item.category.slug  item.pk %}" class="block relative rounded overflow-hidden">
            <img alt="{{ item.name }}" class="h-48 w-full object-cover object-center block rounded-t-xl" src="{{ item.image_url|default_if_none:'/media/item_images/default.png' }}">
            <a href="" class="btn-item-like" id="{{item.id}}"><button class="absolute top-1 right-1 rounded-full w-8 h-8 bg-gray-200 hover:bg-gray-300 p-0 border-0 inline-flex items-center justify-center text-gray-500">
                  <svg {% if request.user in item.liked_by.all %} fill="#f87171" {% else %} fill="currentColor" {% endif%} stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                  <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                </svg>
            </button></a>
        <div class="bg-gray-100 rounded-b-xl p-2">
          <h3 class="text-gray-700 text-xs tracking-widest title-font"> {{ item.category }}</h3>
          <h2 class="text-gray-700 title-font text-base font-medium">{{ item.name }}</h2>
          <p class="text-sm mb-1 text-gray-500 dark:text-gray-400"><span class="mr-1 text-base font-semibold text-gray-700">{% if item.is_usd == True %}${{ item.price|floatformat:0 }}{% else %}{{ item.price|floatformat:0 }} BYN{% endif %} <span class="text-sm font-normal ml-2"> {{ item.location }} обл.</span></p>
		</div>
			</a>
      </div>
      {% endfor %}
      <!--End items loop-->
      </div>



  <div class="rounded-xl mt-8 flex items-center justify-between border-t bg-gray-200 px-4 py-3 sm:px-6">
  <div class="flex flex-1 justify-between sm:hidden">
    <a href="{% if items.has_previous %}?page={{ items.previous_page_number }}{%else%}{%endif%}" class="relative inline-flex items-center rounded-md border {% if items.has_previous %} text-gray-700 bg-white hover:bg-gray-50 focus:z-20 focus:outline-offset-0{%else%} bg-gray-200 text-gray-200 {%endif%}  px-4 py-2 text-sm font-medium">Предыдущая</a>
    <a href="?page={{ items.number }}" aria-current="page" class="rounded-xl relative z-10 inline-flex items-center bg-gray-400 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">{{ items.number }}</a>
    <a href="{% if items.has_next %}?page={{ items.next_page_number }}{%else%}{% endif %}" class="relative inline-flex items-center rounded-md border {% if items.has_next %} text-gray-700 bg-white hover:bg-gray-50 focus:z-20 focus:outline-offset-0{%else%} bg-gray-200 text-gray-200 {%endif%}  px-4 py-2 text-sm font-medium ">Следующая</a>
  </div>
  <div class="hidden sm:flex sm:flex-1 sm:items-center sm:justify-between">
    <div>
      <p class="text-sm text-gray-700">
        На странице
        {% if pagination_items.count >= 10 %}
        <span class="font-medium">10</span>
        {% else %}
        <span class="font-medium">{{ pagination_items.count }}</span>
        {% endif %}
        из
        <span class="font-medium"> {{ pagination_items.count }}</span>
        результатов
      </p>
    </div>
    <div>
      <nav class="isolate inline-flex -space-x-px rounded-md shadow-sm" aria-label="Pagination">
        <a href="{% if items.has_previous %}?page={{ items.previous_page_number }}{%endif%}" class="{% if items.has_previous %} bg-white hover:bg-gray-50 focus:z-20 focus:outline-offset-0{%else%}bg-gray-200{%endif%} relative inline-flex items-center rounded-l-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 ">
          <span class="sr-only">Предыдущая</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd" />
          </svg>
        </a>
        <!-- Current: "z-10 bg-indigo-600 text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", Default: "text-gray-900 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:outline-offset-0" -->
        <a href="?page={{ items.number }}" aria-current="page" class="relative z-10 inline-flex items-center bg-gray-600 px-4 py-2 text-sm font-semibold text-white focus:z-20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">{{ items.number }}</a>
        <a href="{% if items.has_next %}?page={{ items.next_page_number }}{%else%}{% endif %}" class="{% if items.has_next %} bg-white hover:bg-gray-100 focus:z-20 focus:outline-offset-0{%else%}bg-gray-200{%endif%} relative inline-flex items-center rounded-r-md px-2 py-2 text-gray-400 ring-1 ring-inset ring-gray-300">
          <span class="sr-only">Следующая</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
                </svg>
              </a>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>


<script type="text/javascript">
window.CSRF_TOKEN = "{{csrf_token}}"
$(document).on('click', '.btn-item-like', function(){
    var item_id = this.id
    console.log(item_id)
    $.ajax({
        method:"POST",
        url:`/items/${item_id}/like/`,
        data:{item_id:item_id, csrfmiddlewaretoken:window.CSRF_TOKEN}
    });
    window.location.href="http://127.0.0.1:8000/items/"
})
</script>



{% endblock %}