marketplace/blog/urls.py
from django.urls import path
from . import views
from .views import PostLikeToggle

app_name = 'blog'


urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<slug:slug>/", views.blogpost_detail, name="blogpost_detail"),
    path("<slug:slug>/like/", PostLikeToggle.as_view(), name="like-toggle"),
    path("category/<category>/", views.blog_category, name="blog_category"),
    path("<int:pk>/comment_like/", views.like_comment, name="like"),  # is not used right now
]

marketplace/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views
from .forms import LoginForm


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
                                                authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('privacy/', views.user_agreement, name='privacy')
]

marketplace/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new.html/', views.new, name='new'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
    path('<int:pk>/like/', views.like_item, name="like-toggle"),

]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/core/models.py
from django.db import models
from django.conf import settings
from phonenumber_field.modelfields import PhoneNumberField


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = PhoneNumberField(unique=True, blank=False)
    photo = models.ImageField(upload_to='users/%y/%m/%d', blank=True)

    def __str__(self):
        return self.user.username

marketplace/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from betterforms.multiform import MultiModelForm


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ваш никнейм',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email адрес',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Пароль',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Повторите пароль',
        'class': 'w-full py-4 px-6 rounded-xl',
    }))

    # phone_code = forms.CharField(widget=forms.PasswordInput(attrs={
    #     'placeholder': 'sss',
    #     'class': 'w-full py-4 px-6 rounded-xl',
    # }))


class AddUserMultiForm(MultiModelForm):
    form_classes = {
        'user': UserCreationForm,
        'profile': SignUpForm,
    }

marketplace/core/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from blog.models import Post
from .forms import SignUpForm
from django.contrib.auth import logout
from django.contrib import messages
from django.db.models import Q



def logout_view(request):
    logout(request)
    return redirect('/login/')


def index(request):
    items = Item.objects.filter(is_sold=False, is_moderated=True).order_by('created_at').reverse()[0:10]
    posts = Post.objects.all().order_by("-created_on")[0:3]
    categories = Category.objects.all()
    filled_categories = Category.objects.filter()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
        'posts': posts,
        'filled_categories': filled_categories,
    })


def contact(request):
    return render(request, 'core/contact.html')


def user_agreement(request):
    return render(request, 'core/user_agreement.html')


def about(request):
    return render(request, 'core/about.html')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            form.save()
            messages.success(request, f'Добро пожаловать, {username}, Ваш аккаунт успешно создан!')
            return redirect('/login/')

    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

marketplace/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} О нас {% endblock %}
{% block content %}
<div class="md:container px-5 md:mx-auto">
<h2 class="mb-4 text-5xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-5xl dark:text-white"><span class="text-red-600">Race</span>-Marketplace.by</h2>
</div>


<section class="text-gray-600 body-font">
  <div class="container px-5 py-12 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h2 class="sm:text-3xl text-3xl font-bold title-font mb-2 text-gray-900">Кто Мы?</h2>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      <p class="lg:w-1/2 w-full leading-relaxed text-gray-700">Команда любителей <b>Дрифта, Тайм-Аттака и Драг-рейсинга</b>. Этот проект создан для объединения Автолюбителей. Наша цель - облегчить поиск запчастей и спортивных автомобилей</p>
    </div>
      <div class="flex flex-wrap w-full mb-10">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h2 class="sm:text-3xl text-3xl font-bold title-font mb-2 text-gray-900">Разделы сайта</h2>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      <p class="lg:w-1/2 w-full leading-relaxed text-gray-700">В нижеперечисленных карточках Вы найдете основные направления сайта.</p>
    </div>
    <div class="flex flex-wrap -m-4">
      <div class="xl:w-1/4 md:w-1/2 p-4">
         <a href="{% url 'item:items' %}wheelsrims/">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-40 rounded w-full object-cover object-center mb-6" src="/media/blog_images/felgi.png" alt="wheels & rims">
          <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">MARKETPLACE</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font">Шины и Диски</h2>
          <p class="leading-relaxed text-sm">Нестандартные диски и спортивные шины. Как новые, так и б/у.</p>
        </div>
         </a>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <a href="{% url 'item:items' %}cars/">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-40 rounded w-full object-cover object-center mb-6" src="/media/blog_images/e36.jpeg" alt="content">
          <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">MARKETPLACE</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font">Автомобили</h2>
          <p class="leading-relaxed text-sm">К публикации допускаются только доработанные автомобили, либо "заряженные" заводские.</p>
        </div>
        </a>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
        <a href="{% url 'item:items' %}services/">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-40 rounded w-full object-cover object-center mb-6" src="/media/blog_images/ecu.jpeg" alt="content">
          <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">MARKETPLACE</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font">Услуги</h2>
          <p class="leading-relaxed text-sm">Прошивки ЭБУ, сварка кастомного выхлопа или башбара. Установка выворота и многое другое.</p>
        </div>
          </a>
      </div>
      <div class="xl:w-1/4 md:w-1/2 p-4">
      <a href="{% url 'item:items' %}simracing/">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-44 rounded w-full object-cover object-center mb-6" src="/media/core_images/cockpit.webp" alt="content">
          <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">MARKETPLACE</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font">SimRacing</h2>
          <p class="leading-relaxed text-sm"> Рули, шифтеры и педали, а также кокпиты для СимРейсеров.</p>
        </div>
      </a>

      </div>
      <section class="text-gray-600 body-font">
  <div class="container px-5 py-2 mx-auto">
    <div class="flex flex-wrap -mx-4 -mb-10 text-center">
      <div class="sm:w-1/2 mb-10 px-4">
        <a href="{% url 'blog:blog_index' %}">
        <div class="rounded-lg h-64 overflow-hidden">
          <img alt="content" class="object-cover object-center h-full w-full" src="/media/core_images/22rt-trackday.jpeg">
        </div>
        <h2 class="title-font text-2xl font-medium text-gray-900 mt-6 mb-3"><span class="text-red-600">Race</span> Блог</h2>
        <p class="leading-relaxed text-base">Williamsburg occupy sustainable snackwave gochujang. Pinterest cornhole brunch, slow-carb neutra irony.</p>
      </a>
      </div>
      <div class="sm:w-1/2 mb-10 px-4">
        <a href="{% url 'events' %}">
        <div class="rounded-lg h-64 overflow-hidden">
          <img alt="content" class="object-cover object-center h-full w-full" src="/media/blog_images/22rt.jpeg">
        </div>
        <h2 class="title-font text-2xl font-medium text-gray-900 mt-6 mb-3">Календарь</h2>
        <p class="leading-relaxed text-base">Williamsburg occupy sustainable snackwave gochujang. Pinterest cornhole brunch, slow-carb neutra irony.</p>
        </a>
      </div>
    </div>
  </div>
</section>


    </div>
  </div>
</section>




{% endblock %}

marketplace/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Главная страница | Race-Marketplace.pl {% endblock %}
{% block content %}
<div>
    <section class="bg-white dark:bg-gray-900">
    <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-4 lg:grid-cols-12">
        <div class="mr-auto place-self-center lg:col-span-7">
            <h1 class="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">Продажа тюнинг-запчастей и авто в РБ</h1>
            <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">Покупай, продавай и обменивай тюнинг-запчасти онлайн. Все в одном месте с <a class="text-red-600">Race</a>.</p>
            <a href="{% url 'item:items' %}" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                Маркетплейс
            </a>
            <a href="{% url 'core:about' %}" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center">
                О нас
            </a>
        </div>
        <div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <img src="/media/item_images/bmw_m4-removebg-preview.png" alt="bmw m4">
        </div>
    </div>
</section>
</div>
<div class="container mx-auto">
    <div class="flex flex-wrap mt-2">
      <!--Items loop-->
       {% for item in items %}
      <div class="lg:w-1/5 md:w-1/2 p-1 w-full overflow-hidden relative">
        <a href="{% url 'item:detail' item.category.slug  item.pk %}" class="block relative rounded overflow-hidden">
            <img alt="{{ item.name }}" class="h-48 w-full object-cover object-center block rounded-t-xl" src="{{ item.image_url|default_if_none:'/media/item_images/default.png' }}">
        <div class="bg-gray-100 rounded-b-xl p-2">
          <h3 class="text-gray-700 text-xs tracking-widest title-font"> {{ item.category }}</h3>
          <h2 class="text-gray-700 title-font text-base font-medium">{{ item.name }}</h2>
          <p class="text-sm mb-1 text-gray-500 dark:text-gray-400"><span class="mr-1 text-base font-semibold text-gray-700">{% if item.is_usd == True %}${{ item.price|floatformat:0 }}{% else %}{{ item.price|floatformat:0 }} BYN{% endif %} <span class="text-sm font-normal ml-2"> {{ item.location }} обл.</span></p>
		</div>
			</a>
      </div>
      {% endfor %}
      <!--End items loop-->
    </div>
    <div class="leading-none tracking-tight text-center">
        <a href="{% url 'item:items' %}"><button type="button" class="mt-6 mb-10 text-white bg-gray-500 hover:bg-indigo-500 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Перейти в маркетплейс
        <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
        </svg>
        </button></a>
    </div>
</div>


  <div class="mt-8 relative isolate px-6 lg:px-8">
    <div class="mx-auto max-w-2xl py-20 sm:py-20 lg:py-20">

      <div class="text-center">
        <h2 class="text-4xl font-bold tracking-tight text-gray-900 sm:text-6xl"><span class="text-red-600">Race</span> Блог</h2>
        <p class="mt-6 text-lg leading-8 text-gray-600">Фотоотчеты, новости и результаты соревнований, Drift, Time-Attack и Drag. А также календарь автоспортивных мероприятий в Беларуси на 2024 год.</p>
      </div>
    </div>

    <div class="absolute inset-x-0 top-[calc(100%-25rem)] -z-10 transform-gpu overflow-hidden blur-3xl sm:top-[calc(100%-20rem)]" aria-hidden="true">
      <div class="relative left-[calc(50%+3rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 bg-gradient-to-tr from-[#ff80b5] to-[#9089fc] opacity-30 sm:left-[calc(50%+36rem)] sm:w-[72.1875rem]" style="clip-path: polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)"></div>
    </div>
  </div>
</div>




<div class="bg-white py-4 sm:py-2 mb-10">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <dl class="grid grid-cols-1 gap-x-8 gap-y-16 text-center lg:grid-cols-3">
      <div class="mx-auto flex max-w-xs flex-col gap-y-4">
        <dt class="text-base leading-7 text-gray-600">Спортивных мероприятий в календаре</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">100+ </dd>
      </div>
      <div class="mx-auto flex max-w-xs flex-col gap-y-4">
        <dt class="text-base leading-7 text-gray-600">Фотоотчетов и новостей</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">30+</dd>
      </div>
      <div class="mx-auto flex max-w-xs flex-col gap-y-4">
        <dt class="text-base leading-7 text-gray-600">Новых объявлений ежедневно</dt>
        <dd class="order-first text-3xl font-semibold tracking-tight text-gray-900 sm:text-5xl">10+</dd>
      </div>
    </dl>
  </div>
</div>


<section class="text-gray-600 body-font">
  <div class="container px-5 py-6 mx-auto">
    <div class="flex flex-wrap -m-4">
        {% for post in posts %}
      <div class="p-4 md:w-1/3">
        <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden">
                        <a href="{% url 'blog:blogpost_detail' post.slug %}">
          <img class="lg:h-48 md:h-36 w-full object-cover object-center" src="{{ post.image_url|default_if_none:'/media/item_images/default.png' }}" alt="blog">
            </a>
            <div class="p-6">
            <h2 class="tracking-widest text-xs title-font font-medium text-gray-400 mb-1">{{ post.created_on.date }}</h2>
            <h3 class="title-font text-lg font-medium text-gray-900 mb-3">{{ post.title }}</h3>
            <p class="leading-relaxed mb-3">{{ post.descr }}</p>
            <div class="flex items-center flex-wrap ">
              <a href="{% url 'blog:blogpost_detail' post.slug %}" class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0">Читать
                <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M5 12h14"></path>
                  <path d="M12 5l7 7-7 7"></path>
                </svg>
              </a>
              <span class="text-gray-400 mr-3 inline-flex items-center lg:ml-auto md:ml-0 ml-auto leading-none text-sm pr-3 py-1 border-r-2 border-gray-200">
                <svg class="w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="1 0 25 25" stroke-width="1.5" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path></svg> {{ post.likes.count }}
              </span>
              <span class="text-gray-400 inline-flex items-center leading-none text-sm">
                <svg class="w-4 h-4 mr-1" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" viewBox="0 0 24 24">
                  <path d="M21 11.5a8.38 8.38 0 01-.9 3.8 8.5 8.5 0 01-7.6 4.7 8.38 8.38 0 01-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 01-.9-3.8 8.5 8.5 0 014.7-7.6 8.38 8.38 0 013.8-.9h.5a8.48 8.48 0 018 8v.5z"></path>
                </svg> {{ post.comments.count }} 6
              </span>
            </div>
          </div>
        </div>
      </div>
        {% endfor %}
    </div>
  </div>
</section>
          <div class="hidden sm:mb-8 sm:flex sm:justify-center">
              <div class="relative rounded-full px-3 py-2 text-sm leading-6 text-gray-600 ring-1 ring-gray-900/10 hover:ring-gray-900/20">
          И многое другое в нашем<a href="{% url 'blog:blog_index' %}" class="font-semibold text-indigo-600"><span class="absolute inset-0" aria-hidden="true"></span> Блоге <span aria-hidden="true">&rarr;</span></a>
        </div>
      </div>

<!--        <div class="mt-10 flex items-center justify-center gap-x-6">-->
<!--          <a href="{% url 'blog:blog_index' %}" class="rounded-md bg-gray-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Блог</a>-->
<!--          <a href="#" class="text-sm font-semibold leading-6 text-gray-900">Календарь <span aria-hidden="true">→</span></a>-->
<!--        </div>-->



<!--<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">-->

<!--    <h2 class="mb-6 text-2xl font-bold dark:text-white text-center">Популярные категории</h2>-->
<!--    <div class="grid 2xl:grid-cols-6 gap-3 md:grid-cols-6 sm:grid-cols-1">-->
<!--        {% for category in filled_categories %}-->
<!--        {% if category.items.count > 0 %}-->
<!--            <div>-->
<!--                <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">-->
<!--                    <div class="p-2  bg-white rounded-xl">-->
<!--                        <h2 class="text-base">{{ category.name }}</h2>-->
<!--                        <p class="text-sm text-gray-500">Объявлений: {{ category.items.count }}</p>-->
<!--                    </div>-->
<!--                </a>-->
<!--            </div>-->
<!--        {% endif %}-->
<!--        {% endfor %}-->
<!--    </div>-->
<!--</div>-->

<!-- Partners block -->
<div class="bg-white py-24 sm:py-24">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
      <h2 class="text-center text-4xl font-bold leading-none tracking-tight text-gray-900 md:text-4xl lg:text-4xl dark:text-white">Наши партнеры</h2>
    <div class="mx-auto mt-20 grid max-w-lg grid-cols-4 items-center gap-x-8 gap-y-10 sm:max-w-xl sm:grid-cols-6 sm:gap-x-10 lg:mx-0 lg:max-w-none lg:grid-cols-5">
        <a href="https://www.instagram.com/22rt_trackday/"><img class="col-span-2 max-h-20 w-full object-contain lg:col-span-1" src="/media/core_images/22rt_logo.png" alt="Transistor" width="158" height="48"></a>
        <a href="https://racing.by"><img class="col-span-2 max-h-20 w-full object-contain lg:col-span-1" src="/media/core_images/r1.png" alt="Reform" width="158" height="48"></a>
        <a href="https://www.instagram.com/tumanov_photo/"><img class="col-span-2 max-h-20 w-full object-contain lg:col-span-1" src="/media/core_images/tumanov.png" alt="Tuple" width="158" height="48"></a>
        <a href="https://www.instagram.com/erafar.by"><img class="col-span-2 max-h-16 w-full object-contain sm:col-start-2 lg:col-span-1" src="/media/core_images/erafar.png" alt="racing.by" width="168" height="48"></a>
      <img class="col-span-2 col-start-2 max-h-12 w-full object-contain sm:col-start-auto lg:col-span-1" src="https://tailwindui.com/img/logos/158x48/statamic-logo-gray-900.svg" alt="Statamic" width="158" height="48">
    </div>
  </div>
</div>
<!-- End Partners block -->

{% endblock %}

marketplace/core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %}Войти в аккаунт{% endblock %}
{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Вход в систему</h1>
    <form class="max-w-md mx-auto" id="login_form" method="post" action=".">
        {% csrf_token %}
    <div class="relative z-0 w-full mb-5 group">
        <input name="username" id="username" class="block py-2.5 px-0 w-full text-sm text-gray-900 bg-transparent border-0 border-b-2 border-gray-300 appearance-none dark:text-white dark:border-gray-600 dark:focus:border-blue-500 focus:outline-none focus:ring-0 focus:border-blue-600 peer" placeholder=" " required />
        <label for="username" class="peer-focus:font-medium absolute text-sm text-gray-500 dark:text-gray-400 duration-300 transform -translate-y-6 scale-75 top-3 -z-10 origin-[0] peer-focus:start-0 rtl:peer-focus:translate-x-1/4 rtl:peer-focus:left-auto peer-focus:text-blue-600 peer-focus:dark:text-blue-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:translate-y-0 peer-focus:scale-75 peer-focus:-translate-y-6">Никнейм</label>
    </div>
    <div class="mb-3">
        <label class="inline-block mb-2">Пароль </label><br>
        {{ form.password }}
    </div>
    <div class="flex justify-center">
        <button id="submit_btn" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Войти</button>
    </div>
            {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
        {% else %}
        {% endif %}
    </form>
</div>
{% endblock %}

marketplace/core/templates/core/signup.html
{% extends 'core/base.html' %}


{% block title %}Регистрация{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Регистрация</h1>
    <form id="registration_form" method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Никнейм:</label><br>
            {{ form.username }}
            </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email:</label><br>
            {{ form.email }}
            </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Имейл:</label><br>
            {{ form.password1 }}
            </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Повторите пароль:</label><br>
            {{ form.password2 }}
            </div>
        {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
            {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="flex justify-center">
            <button id="submit_btn" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800">Регистрация</button>
        </div>
    </form>
</div>
{% endblock %}