marketplace/blog/urls.py
from django.urls import path
from . import views
from .views import PostLikeToggle

app_name = 'blog'


urlpatterns = [
    path("", views.blog_index, name="blog_index"),
    path("<slug:slug>/", views.blogpost_detail, name="blogpost_detail"),
    path("<slug:slug>/like/", PostLikeToggle.as_view(), name="like-toggle"),
    path("category/<category>/", views.blog_category, name="blog_category"),
    path("<int:pk>/comment_like/", views.like_comment, name="like"),  # is not used right now
]

marketplace/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('dashboard/', views.index, name='index'),
    path('account/', views.account, name='account'),
    path('favorites/', views.favorites, name='favorites'),
    path('seller/<slug:pk>', views.seller_detail, name='seller_detail'),
    path('moder123moder/', views.moderation, name='moderation')
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketplace/blog/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User



class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    body = models.TextField()
    descr = models.TextField()
    image = models.ImageField(upload_to='blog_images', blank=True, null=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='post_likes')
    created_on = models.DateTimeField(auto_now_add=True)
    post_author = models.ForeignKey(User, related_name='post_created_by', on_delete=models.CASCADE, default="nickitque")
    last_modified = models.DateTimeField(auto_now=True)
    categories = models.ManyToManyField("Category", related_name="posts")

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

    def get_absolute_url(self):
        return reverse("blog:blogpost_detail", kwargs={"slug": self.slug})

    def get_like_url(self):
        return reverse("blog:like-toggle", kwargs={"id": self.slug})

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, related_name='comment_created_by', on_delete=models.CASCADE)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='comment_likes')

    class Meta:
        ordering = ('created_on',)

    def __str__(self):
        return f"{self.author} on '{self.post}'"

marketplace/blog/forms.py
from .models import Post, Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

marketplace/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import RedirectView
from .models import Post, Comment
from .forms import CommentForm


def blog_index(request):
    posts = Post.objects.all().order_by("-created_on")
    # add filtering the comments by post
    comments = Comment.objects.filter()
    return render(request, "blog/index.html", {
        "posts": posts,
        "comments": comments,
    })


def blog_category(request, category):
    posts = Post.objects.filter(
        categories__name__contains=category
    ).order_by("-created_on")
    context = {
        "category": category,
        "posts": posts,
        "logged_user": request.user,
    }
    return render(request, "blog/category.html", context)


def blogpost_detail(request, slug):
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        new_comment = comment_form.save(commit=False)
        new_comment.author = request.user
        post_id = request.POST.get('post_id')
        post = get_object_or_404(Post, id=post_id)
        new_comment.post = post
        new_comment.save()

    else:
        comment_form = CommentForm()

    post = Post.objects.get(slug=slug)
    posts = Post.objects.all()
    comments = Comment.objects.filter(post=post)
    related_posts = Post.objects.filter()

    context = {
        "post": post,
        "posts": posts,
        "comments": comments,
        "comment_form": comment_form,
        "related_posts": related_posts,
    }

    return render(request, "blog/detail.html", context)


class PostLikeToggle(RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        slug = self.kwargs.get("slug")
        obj = Post.objects.get(slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        if user.is_authenticated:
            if user in obj.likes.all():
                obj.likes.remove(user)
            else:
                obj.likes.add(user)
        return url_


def like_comment(request, pk):
    """Is not used right now"""
    comment = get_object_or_404(Comment, id=pk)

    if comment.likes.filter(id=request.user.id).exists():
        comment.likes.remove(request.user)
    else:
        comment.likes.add(request.user)

marketplace/blog/templates/blog/blank.html
    <!-- Sidebar -->
<div class="flex">
    <div class="rounded-xl bg-indigo-900 w-64">
        <div class="rounded-xl bg-indigo-800">
            <div class="text-gray-200 p-5 text-xl font-bold">
                Панель управления
            </div>
            </div>
            <div>
<div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 21">
                  <path d="M16.975 11H10V4.025a1 1 0 0 0-1.066-.998 8.5 8.5 0 1 0 9.039 9.039.999.999 0 0 0-1-1.066h.002Z"/>
                  <path d="M12.5 0c-.157 0-.311.01-.565.027A1 1 0 0 0 11 1.02V10h8.975a1 1 0 0 0 1-.935c.013-.188.028-.374.028-.565A8.51 8.51 0 0 0 12.5 0Z"/>
               </svg>
               <span class="ms-3">Dashboard</span>
            </a>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                  <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Kanban</span>
               <span class="inline-flex items-center justify-center px-2 ms-3 text-sm font-medium text-gray-800 bg-gray-100 rounded-full dark:bg-gray-700 dark:text-gray-300">Pro</span>
            </a>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="m17.418 3.623-.018-.008a6.713 6.713 0 0 0-2.4-.569V2h1a1 1 0 1 0 0-2h-2a1 1 0 0 0-1 1v2H9.89A6.977 6.977 0 0 1 12 8v5h-2V8A5 5 0 1 0 0 8v6a1 1 0 0 0 1 1h8v4a1 1 0 0 0 1 1h2a1 1 0 0 0 1-1v-4h6a1 1 0 0 0 1-1V8a5 5 0 0 0-2.582-4.377ZM6 12H4a1 1 0 0 1 0-2h2a1 1 0 0 1 0 2Z"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Inbox</span>
               <span class="inline-flex items-center justify-center w-3 h-3 p-3 ms-3 text-sm font-medium text-blue-800 bg-blue-100 rounded-full dark:bg-blue-900 dark:text-blue-300">3</span>
            </a>
         </li>
         <li>
           <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 18">
                  <path d="M14 2a3.963 3.963 0 0 0-1.4.267 6.439 6.439 0 0 1-1.331 6.638A4 4 0 1 0 14 2Zm1 9h-1.264A6.957 6.957 0 0 1 15 15v2a2.97 2.97 0 0 1-.184 1H19a1 1 0 0 0 1-1v-1a5.006 5.006 0 0 0-5-5ZM6.5 9a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9ZM8 10H5a5.006 5.006 0 0 0-5 5v2a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-2a5.006 5.006 0 0 0-5-5Z"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Users</span>
            </a>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 20">
                  <path d="M17 5.923A1 1 0 0 0 16 5h-3V4a4 4 0 1 0-8 0v1H2a1 1 0 0 0-1 .923L.086 17.846A2 2 0 0 0 2.08 20h13.84a2 2 0 0 0 1.994-2.153L17 5.923ZM7 9a1 1 0 0 1-2 0V7h2v2Zm0-5a2 2 0 1 1 4 0v1H7V4Zm6 5a1 1 0 1 1-2 0V7h2v2Z"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Products</span>
            </a>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 16">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 8h11m0 0L8 4m4 4-4 4m4-11h3a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-3"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Sign In</span>
            </a>
         </li>
         <li>
            <a href="#" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
               <svg class="flex-shrink-0 w-5 h-5 text-gray-500 transition duration-75 dark:text-gray-400 group-hover:text-gray-900 dark:group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M5 5V.13a2.96 2.96 0 0 0-1.293.749L.879 3.707A2.96 2.96 0 0 0 .13 5H5Z"/>
                  <path d="M6.737 11.061a2.961 2.961 0 0 1 .81-1.515l6.117-6.116A4.839 4.839 0 0 1 16 2.141V2a1.97 1.97 0 0 0-1.933-2H7v5a2 2 0 0 1-2 2H0v11a1.969 1.969 0 0 0 1.933 2h12.134A1.97 1.97 0 0 0 16 18v-3.093l-1.546 1.546c-.413.413-.94.695-1.513.81l-3.4.679a2.947 2.947 0 0 1-1.85-.227 2.96 2.96 0 0 1-1.635-3.257l.681-3.397Z"/>
                  <path d="M8.961 16a.93.93 0 0 0 .189-.019l3.4-.679a.961.961 0 0 0 .49-.263l6.118-6.117a2.884 2.884 0 0 0-4.079-4.078l-6.117 6.117a.96.96 0 0 0-.263.491l-.679 3.4A.961.961 0 0 0 8.961 16Zm7.477-9.8a.958.958 0 0 1 .68-.281.961.961 0 0 1 .682 1.644l-.315.315-1.36-1.36.313-.318Zm-5.911 5.911 4.236-4.236 1.359 1.359-4.236 4.237-1.7.339.341-1.699Z"/>
               </svg>
               <span class="flex-1 ms-3 whitespace-nowrap">Sign Up</span>
            </a>
         </li>
      </ul>
   </div>
        </div>
    </div>

marketplace/blog/templates/blog/category.html
{% extends 'core/base.html' %}
{% load blog_navbar %}
{% block title %} Новости {% endblock %}
{% block content %}


<div class="container mx-auto">

    {% blog_navbar %}

    <div class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-gray-200 pt-10 sm:mt-8 sm:pt-16 lg:mx-0 lg:max-w-none lg:grid-cols-3">
      {% for post in posts %}
        <article class="flex max-w-xl flex-col items-start justify-between">
        <div class="flex items-center gap-x-4">
           <h3 class="mt-3 text-xl font-semibold leading-6 text-gray-900 hover:text-gray-500">
            <a href="{% url 'blog:blogpost_detail' post.slug %}">
                {{ post.title }}
            </a>
          </h3>
        </div>
        <img class="mt-2 h-48 w-full object-cover rounded-xl" src="{{ post.image_url|default_if_none:'/media/item_images/default.png' }}" alt="{{ post.title }}">
        <div class="mt-3 group relative text-xs">
          <a id="{{ post.slug }}" href="" class="btn-post-like">
              <span class="relative z-10 rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">
        <button>
            <svg class="w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" {% if logged_user in post.likes.all %} {% else %} fill="none" {% endif %} viewBox="1 -4 25 25" stroke-width="1.5" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path></svg>
        </button>{{ post.likes.count }}</span></a>

         <time datetime="2020-03-16" class="text-gray-500">{{ post.created_on.date }}</time>
        {% for category in post.categories.all %}
          <a href="{% url 'blog:blog_category' category.name %}" class="relative z-10 rounded-full bg-gray-50 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-100">{{ category.name }}</a>
            <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">{{ post.body | safe | slice:":200" }}...</p>
        </div>
        <div class="relative mt-6 flex items-center gap-x-4">
          <img src="https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" class="h-10 w-10 rounded-full bg-gray-50">
          <div class="text-sm leading-6">
            <p class="font-semibold text-gray-900">
              <a href="#">
                <span class="absolute inset-0"></span>
                Michael Foster
              </a>
            </p>
            <p class="text-gray-600">Co-Founder / CTO</p>
          </div>
        </div>
      </article>
                {% endfor %}

        {% endfor %}
    </div>
  </div>
</div>






<script type="text/javascript">
window.CSRF_TOKEN = "{{csrf_token}}"
$(document).on('click', '.btn-post-like', function(){
    var post_id = this.id
    console.log(post_id)
    $.ajax({
        method:"POST",
        url:`/blog/${post_id}/like/`,
        data:{post_id:post_id, csrfmiddlewaretoken:window.CSRF_TOKEN}
    })
    window.location.href="http://127.0.0.1:8000/blog/"
})
</script>

{% endblock %}

marketplace/blog/templates/blog/index.html
{% extends 'core/base.html' %}
{% load blog_navbar %}

{% block title %} Новости {% endblock %}
{% block content %}
<p>sadsad</p>
            {% for comment in comments %}
            {{ comment.post.id }}
            {% endfor %}
<div class="container mx-auto">
{% blog_navbar %}
    <div class="mx-auto mt-10 grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 border-t border-gray-200 pt-10 sm:mt-8 sm:pt-10 lg:mx-0 lg:max-w-none lg:grid-cols-3">
      {% for post in posts %}
        <article class="flex max-w-xl flex-col items-start justify-between">
        <div class="flex items-center gap-x-4">
           <h3 class="mt-3 mb-2 text-xl font-semibold leading-6 text-gray-900 hover:text-gray-500">
            <a href="{% url 'blog:blogpost_detail' post.slug %}">
                {{ post.title }}
            </a>
          </h3>
        </div>
        <img class="h-48 w-full object-cover rounded-xl" src="{{ post.image_url|default_if_none:'/media/item_images/default.png' }}" alt="{{ post.title }}">
        <div class="mt-3 group relative text-xs">
          <a id="{{ post.slug }}" href="" class="btn-post-like">
          <span class="relative mr-2 z-10 rounded-full bg-gray-100 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-300">
            <button>
                <svg class="w-4 h-4 mr-1" xmlns="http://www.w3.org/2000/svg" {% if request.user in post.likes.all %} fill="#f87171"  {% else %} fill="none" stroke="currentColor" {% endif %} viewBox="1 -4 25 25" stroke-width="1.5"> <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"></path></svg>
            </button>{{ post.likes.count }}
            {% for comment in comments %}
              {% if comment.post.id == post.id %}
              hello
              {% else %}
              {% endif %}
            {% endfor %}
          </span></a>

        {% for category in post.categories.all %}
          <a href="{% url 'blog:blog_category' category.name %}" class="relative mr-2 z-10 rounded-full bg-gray-200 px-3 py-1.5 font-medium text-gray-600 hover:bg-gray-300">{{ category.name }}</a>
             <time datetime="2020-03-16" class="text-gray-500">{{ post.created_on.date }}</time>
            <p class="mt-5 line-clamp-3 text-sm leading-6 text-gray-600">{{ post.descr | safe }}</p>
        </div>
        <div class="relative mt-1 flex items-center gap-x-4">
          <img src="/media/core_images/22rt_logo.jpeg" alt="" class="h-10 w-10 rounded-full bg-gray-50">
          <div class="text-sm leading-6">
            <p class="font-semibold text-gray-900">
              <a href="{% url 'dashboard:seller_detail' post.post_author.id %}">
                <span class="absolute inset-0"></span>
                {{ post.post_author }}
              </a>
            </p>
            <p class="text-gray-600">Race-Marketplace Team</p>
          </div>
        </div>
      </article>
        {% endfor %}
    {% endfor %}
    </div>
  </div>
</div>






<script type="text/javascript">
window.CSRF_TOKEN = "{{csrf_token}}"
$(document).on('click', '.btn-post-like', function(){
    var post_slug = this.id
    console.log(post_slug)
    $.ajax({
        method:"POST",
        url:`/blog/${post_slug}/like/`,
        data:{post_slug:post_slug, csrfmiddlewaretoken:window.CSRF_TOKEN}
    })
    window.location.href="http://127.0.0.1:8000/blog/"
})
</script>

{% endblock %}